### PR TITLE
Remove the self_hosted_engine role

### PR DESCRIPTION
**Pull request by kobihk**
We need to remove it since there are no enabled repository
on hosted engine vm and if we run it we will get the following error:
  "There are no enabled repos..."

### CODE REVIEW

**Comment by fabianvf** [comment]
Rather than removing it, in the self-hosted.yml playbook we could replace 
```
- self_hosted_engine
```

with

```
- { role: self_hosted_engine, when: '{{ repositories|length > 0 }}'}
```

That way it will only update when repositories have been enabled.

**Comment by fabianvf** [comment]
Also merge conflicts.

**Comment by kobihk** [comment]
adopt your suggestion and resolved the conflicts ;-)

**Comment by fabianvf** [comment]
:+1:

**Pull request merged**
