### PR TITLE
Added the option to deploy without ansible in 4.2

### PR DESCRIPTION
**Pull request by kobihk**
Since in 4.2 we start running deploy with ansible by default and we
can't use it like that because we using custom cloud init image
we have to add --noansible to our deploy.

Also one SElinux change related to:
   https://bugzilla.redhat.com/show_bug.cgi?id=1418579

### CODE REVIEW

**Comment by fabianvf** [comment]
LGTM. Wonder if we can remove the custom cloud init image at this point.

**Comment by kobihk** [comment]
Thanks @fabianvf !!!
For now when we need to support deploy of 4.1 and 4.2 and the ansible deploy is relevant only for 4.2.
IMHO we need to keep this custom cloud-init image.
BTW I working on a patch to support ansible deploy with 4.2, I'll upload it when it will be ready :)

**Comment by fabianvf** [comment]
That makes sense. I wonder if maybe we should tag and branch at some point, if we don't need that cruft for the newest version of ovirt. Don't have a strong opinion on it though, just would like to remove workarounds as we're able.

**Comment by kobihk** [comment]
From my point of view (for now), it's better to use master for the 2 latest versions 4.1 and 4.2 
about tagging, I think it has no big impact on the branch so you can add it whenever you need.

**Pull request merged**
